/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFAdministrarCategoria.java
 *
 * Created on 26/05/2010, 06:04:06 PM
 */

package antiplagium.view;

import antiplagium.BE.CategoriaBE;
import antiplagium.BE.UsuarioBE;
import antiplagium.BL.CategoriaBL;
import antiplagium.BL.UsuarioBL;
import java.awt.BorderLayout;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author a20057070
 */
public class JDAdministrarCategoria extends JDialog {


    ArrayList<Integer> alistIdsCategorias=null;
    int opcion;
    CategoriaBE objCategoriaSeleccionada=null;

    ArrayList<CategoriaBE> alstResultado = null;


    /** Creates new form JFAdministrarCategoria */


    public JDAdministrarCategoria() {
        initComponents();        
        tbCategoria.getColumnModel().removeColumn(tbCategoria.getColumnModel().getColumn(3));
        btnAceptar.setVisible(false);



    }

    public JDAdministrarCategoria(String nombreCategoria ){
        initComponents();
        
        if(nombreCategoria==null){
            if (tbCategoria.getColumnModel().getColumnCount()==3){
                tbCategoria.getColumnModel().addColumn(tbCategoria.getColumnModel().getColumn(3));

            }
            opcion=1;
        }
        else {
            tbCategoria.getColumnModel().removeColumn(tbCategoria.getColumnModel().getColumn(3));
            this.txtNombre.setText(nombreCategoria);
            btnAceptar.setText("Seleccionar");
            opcion=2;
        }
        btnAceptar.setVisible(true);
        mnuRegistrarCategoria.setVisible(false);
        mnuModificarCategoria.setVisible(false);
        buscar();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatosBusqueda = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        pnlResultadosBusqueda = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCategoria = new javax.swing.JTable();
        btnCerrar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnAceptar1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuRegistrarCategoria = new javax.swing.JMenu();
        mnuModificarCategoria = new javax.swing.JMenu();

        setTitle("Adiminstrar Categoria");
        setModal(true);

        pnlDatosBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de Búsqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), java.awt.Color.blue)); // NOI18N

        lblNombre.setText("Nombre");

        lblDescripcion.setText("Descripción");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setMaximumSize(new java.awt.Dimension(135, 35));
        btnBuscar.setMinimumSize(new java.awt.Dimension(135, 35));
        btnBuscar.setPreferredSize(new java.awt.Dimension(135, 35));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosBusquedaLayout = new javax.swing.GroupLayout(pnlDatosBusqueda);
        pnlDatosBusqueda.setLayout(pnlDatosBusquedaLayout);
        pnlDatosBusquedaLayout.setHorizontalGroup(
            pnlDatosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosBusquedaLayout.createSequentialGroup()
                .addGroup(pnlDatosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosBusquedaLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(pnlDatosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescripcion)
                            .addComponent(lblNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDatosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescripcion)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)))
                    .addGroup(pnlDatosBusquedaLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        pnlDatosBusquedaLayout.setVerticalGroup(
            pnlDatosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pnlDatosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlResultadosBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados de Búsqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), java.awt.Color.blue)); // NOI18N

        tbCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Descripción", "seleccionar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbCategoria);

        javax.swing.GroupLayout pnlResultadosBusquedaLayout = new javax.swing.GroupLayout(pnlResultadosBusqueda);
        pnlResultadosBusqueda.setLayout(pnlResultadosBusquedaLayout);
        pnlResultadosBusquedaLayout.setHorizontalGroup(
            pnlResultadosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultadosBusquedaLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        pnlResultadosBusquedaLayout.setVerticalGroup(
            pnlResultadosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlResultadosBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar.png"))); // NOI18N
        btnCerrar.setText("Cancelar");
        btnCerrar.setMaximumSize(new java.awt.Dimension(135, 35));
        btnCerrar.setMinimumSize(new java.awt.Dimension(135, 35));
        btnCerrar.setPreferredSize(new java.awt.Dimension(135, 35));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setMaximumSize(new java.awt.Dimension(135, 35));
        btnAceptar.setMinimumSize(new java.awt.Dimension(135, 35));
        btnAceptar.setPreferredSize(new java.awt.Dimension(135, 35));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnAceptar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png"))); // NOI18N
        btnAceptar1.setText("Ver Reporte");
        btnAceptar1.setMaximumSize(new java.awt.Dimension(135, 35));
        btnAceptar1.setMinimumSize(new java.awt.Dimension(135, 35));
        btnAceptar1.setPreferredSize(new java.awt.Dimension(135, 35));
        btnAceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar1ActionPerformed(evt);
            }
        });

        mnuRegistrarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nuevo.png"))); // NOI18N
        mnuRegistrarCategoria.setText("Registrar");
        mnuRegistrarCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuRegistrarCategoriaMousePressed(evt);
            }
        });
        jMenuBar1.add(mnuRegistrarCategoria);

        mnuModificarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/modificar.png"))); // NOI18N
        mnuModificarCategoria.setText("Modificar");
        mnuModificarCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuModificarCategoriaMousePressed(evt);
            }
        });
        jMenuBar1.add(mnuModificarCategoria);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlResultadosBusqueda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDatosBusqueda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(btnAceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDatosBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(pnlResultadosBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed
    private void buscar(){
        CategoriaBL objCategoriaBL = new CategoriaBL();
        DefaultTableModel temp = (DefaultTableModel) this.tbCategoria.getModel();
        for (int i=temp.getRowCount() - 1; i >= 0; --i){
            temp.removeRow(i);
        }
        try {
            String temp1 = "";
            for (int i=0; i < this.txtNombre.getText().length(); ++i){
                if (this.txtNombre.getText().charAt(i) != '\''){
                    temp1 += this.txtNombre.getText().charAt(i);
                }
            }
            String temp2 = "";
            for (int i=0; i < this.txtDescripcion.getText().length(); ++i){
                if (this.txtDescripcion.getText().charAt(i) != '\''){
                    temp2 += this.txtDescripcion.getText().charAt(i);
                }
            }
            ArrayList<CategoriaBE> alstResultado = objCategoriaBL.buscarCategoria(temp2,temp1);
            for (int i=0; i < alstResultado.size(); ++i){
                Object[]nuevo ={alstResultado.get(i).getIdCategoria(),alstResultado.get(i).getNombre(),alstResultado.get(i).getDescripcion()};
                temp.addRow(nuevo);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JDAdministrarCategoria.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JDAdministrarCategoria.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JDAdministrarCategoria.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.txtDescripcion.setText("");
        this.txtNombre.setText("");

    }

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        if(opcion==1){
        DefaultTableModel modelo=(DefaultTableModel)tbCategoria.getModel();
        alistIdsCategorias=new ArrayList();
        
        for(int i=0;i<modelo.getRowCount();i++){
            
            Boolean seleccion=(Boolean)modelo.getValueAt(i, 3);
            System.out.println("esto es "+seleccion);
            if ((seleccion!=null)&&(seleccion!=false))
                alistIdsCategorias.add((Integer)modelo.getValueAt(i, 0));
        }

        this.setVisible(false);

        }
        else {

            boolean selecciona=false;

            DefaultTableModel modelo= (DefaultTableModel)tbCategoria.getModel();
            int[] filasSeleccionadas=  tbCategoria.getSelectedRows();

            if (filasSeleccionadas.length==0){
                JOptionPane.showMessageDialog(this,"Debe seleccionar una fila o registro de la lista de usuarios","Error", JOptionPane.ERROR_MESSAGE);
            }
            else if(filasSeleccionadas.length>1){
                JOptionPane.showMessageDialog(this,"Debe seleccionar solo una fila o registro de la lista usuaios","Error", JOptionPane.ERROR_MESSAGE);
            }
            else if(filasSeleccionadas.length==1){
                objCategoriaSeleccionada=CategoriaBL.buscarIdCategoria(Integer.parseInt(tbCategoria.getValueAt(tbCategoria.getSelectedRow(),0).toString()));

                this.setVisible(false);
            }

        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    public CategoriaBE getCategoriaSeleccionado() {
        return objCategoriaSeleccionada;
    }



    public ArrayList<Integer> getIdsCategorias() {
        return alistIdsCategorias;
    }
    private void mnuRegistrarCategoriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuRegistrarCategoriaMousePressed
        // TODO add your handling code here:
        JDRegistrarCategoria registrarCategoria = new JDRegistrarCategoria();
        registrarCategoria.setLocationRelativeTo(this);
        registrarCategoria.setModal(true);
        registrarCategoria.setVisible(true);
    }//GEN-LAST:event_mnuRegistrarCategoriaMousePressed

    private void mnuModificarCategoriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuModificarCategoriaMousePressed
        // TODO add your handling code here:
        int idx = tbCategoria.getSelectedRow();
        if (idx >= 0){
            DefaultTableModel temp = (DefaultTableModel) tbCategoria.getModel();
            int idCategoria = (Integer)temp.getValueAt(idx, 0);
            String nombre = (String)temp.getValueAt(idx, 1);
            String descripcion = (String)temp.getValueAt(idx, 2);
            CategoriaBE objCategoria = new CategoriaBE(idCategoria,descripcion,nombre);
            JDRegistrarCategoria registrarCategoria = new JDRegistrarCategoria(objCategoria);
            registrarCategoria.setLocationRelativeTo(this);
            registrarCategoria.setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar categoria", "Error Modificar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mnuModificarCategoriaMousePressed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
         buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar1ActionPerformed
          Map pars = new HashMap();


        try {
            JasperPrint jasperPrint= Utilitarios.GeneraReportes.gestorReporte("report2", pars, this.alstResultado);

            JRViewer v = new JRViewer(jasperPrint);
            JFrame ventana=new JFrame();
            ventana.getContentPane().add(v,BorderLayout.CENTER);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            ventana.setSize(706, 478);

            ventana.setTitle("Vista Previa");
            ventana.setLocation(512-ventana.getWidth()/2,387 - ventana.getHeight()/2 );

            ventana.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se cuenta con un equipo de impresion");
            e.printStackTrace();
        }        // TODO add your        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptar1ActionPerformed

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAceptar1;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JMenu mnuModificarCategoria;
    private javax.swing.JMenu mnuRegistrarCategoria;
    private javax.swing.JPanel pnlDatosBusqueda;
    private javax.swing.JPanel pnlResultadosBusqueda;
    private javax.swing.JTable tbCategoria;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

}
