/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFEliminarUsuario.java
 *
 * Created on 06/05/2010, 05:01:38 PM
 */

package antiplagium.view;

import antiplagium.BE.EstadoBE;
import antiplagium.BE.UsuarioBE;
import antiplagium.BL.EstadoBL;
import antiplagium.BL.UsuarioBL;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import org.freixas.jcalendar.JCalendarCombo;

/**
 *
 * @author a20030555
 */
public class JDEliminarUsuario extends JDialog{

  JCalendarCombo jCCFechaEliminar = new JCalendarCombo();
    EstadoBL estadoBL;
    UsuarioBL usuarioBL;
    UsuarioBE usuarioBE;
    Boolean rpta=false;
    ArrayList<EstadoBE> registrosEstado;
        /** Creates new form JFEliminarUsuario */
    public JDEliminarUsuario(int idUsuario) {
        try {

            initComponents();
            jCCFechaEliminar.setSize(253, 31);
            jCCFechaEliminar.setEnabled(false);
            jPFechaEliminar.add(jCCFechaEliminar);

            estadoBL = new EstadoBL();
            usuarioBL = new UsuarioBL();
            registrosEstado = estadoBL.ObtenerEstados(0,"","");
            if (registrosEstado != null) {
                //System.out.println(registrosEstado.size());
                int numeroRegistros = registrosEstado.size();
                for (int i = 0; i <= numeroRegistros - 1; i++) {
                    jCBEstado.addItem(registrosEstado.get(i));
                }
            }

            usuarioBE=usuarioBL.getUsuarioBE(idUsuario);

            for(int i=0;i<jCBEstado.getModel().getSize();i++){
                if (usuarioBE.getEstadoBE().getNombre().compareTo(jCBEstado.getItemAt(i).toString())==0){
                        jCBEstado.setSelectedIndex(i);
                }

            }


            //System.out.println(jCBEstado.getSelectedIndex()+jCBEstado.getSelectedItem().toString());
            EstadoBE estadoBE=(EstadoBE)jCBEstado.getSelectedItem();
            if (estadoBE.getNombre().compareTo("Inactivo")==0){
                jCCFechaEliminar.setDate(usuarioBE.getFechaCese());
                JOptionPane.showMessageDialog(this,"El usuario seleccionado ya ha sido eliminado.", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
                rpta=false;
                jCCFechaEliminar.setEnabled(false);
                jBAceptarEliminar.setEnabled(false);
                jCBEstado.setEnabled(false);
            }

            jLabel4.setText(usuarioBE.getNombres()+" "+usuarioBE.getApellidoPaterno());

        } catch (SQLException ex) {
            Logger.getLogger(JDEliminarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JDEliminarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPFechaEliminar = new javax.swing.JPanel();
        jCBEstado = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBAceptarEliminar = new javax.swing.JButton();
        jBCancelarEliminar = new javax.swing.JButton();

        setTitle("Eliminar Usuario");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Eliminar"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setText("El usuario");

        jLabel2.setText("Fecha");

        jPFechaEliminar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPFechaEliminar.setPreferredSize(new java.awt.Dimension(200, 30));

        javax.swing.GroupLayout jPFechaEliminarLayout = new javax.swing.GroupLayout(jPFechaEliminar);
        jPFechaEliminar.setLayout(jPFechaEliminarLayout);
        jPFechaEliminarLayout.setHorizontalGroup(
            jPFechaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );
        jPFechaEliminarLayout.setVerticalGroup(
            jPFechaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        jCBEstado.setEnabled(false);
        jCBEstado.setPreferredSize(new java.awt.Dimension(200, 30));
        jCBEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBEstadoActionPerformed(evt);
            }
        });

        jLabel3.setText("Estado");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText(" ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel5.setText("procederá a ser eliminado.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(52, 52, 52)
                            .addComponent(jPFechaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPFechaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBAceptarEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png"))); // NOI18N
        jBAceptarEliminar.setText("Aceptar");
        jBAceptarEliminar.setPreferredSize(new java.awt.Dimension(135, 35));
        jBAceptarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarEliminarActionPerformed(evt);
            }
        });

        jBCancelarEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar.png"))); // NOI18N
        jBCancelarEliminar.setText("Cancelar");
        jBCancelarEliminar.setPreferredSize(new java.awt.Dimension(135, 35));
        jBCancelarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBAceptarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBCancelarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAceptarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCancelarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAceptarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarEliminarActionPerformed


        usuarioBE.setFechaCese(jCCFechaEliminar.getDate());
        //usuarioBE.setTipoCeseBE(null);
        for (int i=0;i<registrosEstado.size();i++){
            if (registrosEstado.get(i).getNombre().compareTo("Inactivo")==0){
                usuarioBE.setEstadoBE(registrosEstado.get(i));
            }
        }
        rpta=usuarioBL.ElminarUsuario(usuarioBE);

        if(rpta==true){
            JOptionPane.showMessageDialog(this,"El usuario ha sido eliminado con exito.", "Informe", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this,"Error. Usuario no eliminado", "Error", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_jBAceptarEliminarActionPerformed

    private void jBCancelarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarEliminarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBCancelarEliminarActionPerformed

    private void jCBEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBEstadoActionPerformed

    /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JFEliminarUsuario().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptarEliminar;
    private javax.swing.JButton jBCancelarEliminar;
    private javax.swing.JComboBox jCBEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPFechaEliminar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
