/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RegistrarCategoria.java
 *
 * Created on 01/05/2010, 04:19:50 PM
 */

package antiplagium.view;

import antiplagium.BE.CategoriaBE;
import antiplagium.BE.GestorTiposOperacion;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.freixas.jcalendar.JCalendarCombo;
import antiplagium.BE.Utilitario;
import javax.swing.JOptionPane;
import antiplagium.BL.CategoriaBL;
import antiplagium.DAL.ConexionJDBC;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JFrame;
/**
 *
 * @author PATTY
 */


public class JDRegistrarCategoria extends JDialog {
    private int TipoOperacion;
    private CategoriaBE objCategoria;
    /** Creates new form RegistrarCategoria */
    public JDRegistrarCategoria() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        TipoOperacion = 0;
        int idCategoria = 1;
        try {
            idCategoria = Utilitario.generaCodigo("Categoria");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JDRegistrarCategoria.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JDRegistrarCategoria.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtIdCategoria.setText("" + idCategoria + "");
    }

    public JDRegistrarCategoria(CategoriaBE objCategoria){
        initComponents();
        TipoOperacion = 1;
        txtIdCategoria.setText("" + objCategoria.getIdCategoria() + "");
        txtDescCategoria.setText(objCategoria.getDescripcion());
        txtNomCategoria.setText(objCategoria.getNombre());
        this.objCategoria = objCategoria;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIdCategoria = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        lblDescripcion = new javax.swing.JLabel();
        txtNomCategoria = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        txtDescCategoria = new javax.swing.JTextField();
        txtIdCategoria = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Categoria");
        setModal(true);
        setName("JDRegistrarCategoria"); // NOI18N
        setResizable(false);

        lblIdCategoria.setText("Código:");

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setMaximumSize(new java.awt.Dimension(135, 35));
        btnLimpiar.setMinimumSize(new java.awt.Dimension(135, 35));
        btnLimpiar.setPreferredSize(new java.awt.Dimension(135, 35));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblDescripcion.setText("Descripción:");

        txtNomCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomCategoriaKeyReleased(evt);
            }
        });

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setMaximumSize(new java.awt.Dimension(135, 35));
        btnAceptar.setMinimumSize(new java.awt.Dimension(135, 35));
        btnAceptar.setPreferredSize(new java.awt.Dimension(135, 35));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setMaximumSize(new java.awt.Dimension(135, 35));
        btnCancelar.setMinimumSize(new java.awt.Dimension(135, 35));
        btnCancelar.setPreferredSize(new java.awt.Dimension(135, 35));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre:");

        txtDescCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescCategoriaKeyReleased(evt);
            }
        });

        txtIdCategoria.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescripcion)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblIdCategoria)
                                    .addComponent(lblNombre))))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNomCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                                .addComponent(txtDescCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(146, 146, 146))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdCategoria)
                    .addComponent(txtIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(txtDescCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        /* Revisamos si los campos nombre y descripcion son vacios */
        if ((txtNomCategoria.getText().compareTo("") == 0)){
            JOptionPane.showMessageDialog(this,"El campo Nombre no puede ser vacio","Error Registro",JOptionPane.ERROR_MESSAGE);
            return;
        }
        else if ( (txtDescCategoria.getText().compareTo("") == 0) ){
            JOptionPane.showMessageDialog(this,"El campo Descripción no puede ser vacio","Error Registro",JOptionPane.ERROR_MESSAGE);
            return;
        }
        else {
            boolean boolExito = false;
            CategoriaBL objCategoriaBL = new CategoriaBL();
            CategoriaBE objCategoriaTemporal = new CategoriaBE(Integer.parseInt(txtIdCategoria.getText()),txtDescCategoria.getText(),txtNomCategoria.getText());
            try {
                    if (TipoOperacion==0){
                        boolExito = objCategoriaBL.registrarCategoria(objCategoriaTemporal);
                    }
                    else {
                        boolExito = objCategoriaBL.modificarCategoria(objCategoriaTemporal);
                    }
                } catch (Exception ex) {
                    Logger.getLogger(JDRegistrarCategoria.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (boolExito) {
                    if (TipoOperacion==0){
                        try {
                            String descripcion = GestorTiposOperacion.getTipoOperacion("registra") + "\n";
                            descripcion += "Registro nuevo: " + objCategoriaTemporal.getNombre() + "\n";
                            descripcion += "Descripción: " + objCategoriaTemporal.getDescripcion();
                            JFBase.setOperacion(this.getName(), GestorTiposOperacion.getTipoOperacion("registra"), descripcion);
                            JFBase.registrarOperacion();
                            ConexionJDBC.cerrarConexion();
                        } catch (SQLException ex) {
                            Logger.getLogger(JDRegistrarCategoria.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        JOptionPane.showMessageDialog(this, "La categoria ha sido registrada con éxito", "Modificar Categoria",JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                        try {
                            String descripcion = GestorTiposOperacion.getTipoOperacion("modifica") + "\n";
                            descripcion += "Registro original:\n";
                            descripcion += objCategoria.getNombre() + "\n";
                            descripcion += "Descripción: " + objCategoria.getDescripcion() + "\n";
                            descripcion += "Registro modificado:\n";
                            descripcion += objCategoriaTemporal.getNombre() + "\n";
                            descripcion += "Descripción: " + objCategoriaTemporal.getDescripcion();
                            JFBase.setOperacion(this.getName(), GestorTiposOperacion.getTipoOperacion("modifica"), descripcion);
                            JFBase.registrarOperacion();
                            ConexionJDBC.cerrarConexion();
                        } catch (SQLException ex) {
                            Logger.getLogger(JDRegistrarCategoria.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        JOptionPane.showMessageDialog(this, "La categoria ha sido modificada con éxito", "Modifcar Categoria",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
                this.dispose();
        }
}//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
       if (TipoOperacion == 1){
            txtNomCategoria.setText(objCategoria.getNombre());
            txtDescCategoria.setText(objCategoria.getDescripcion());
       }
       else {
            txtNomCategoria.setText("");
            txtDescCategoria.setText("");
       }
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtNomCategoriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomCategoriaKeyReleased
        // TODO add your handling code here:
        Character caracter = new Character(evt.getKeyChar());

        if (!Utilitario.esLetra(caracter)) {
                    String texto = "";
                    for (int i = 0; i < txtNomCategoria.getText().length(); i++)
                        if (Utilitario.esLetra(new Character(txtNomCategoria.getText().charAt(i))))
                            texto += txtNomCategoria.getText().charAt(i);
                        txtNomCategoria.setText(texto);
                txtNomCategoria.getToolkit().beep();
        }
    }//GEN-LAST:event_txtNomCategoriaKeyReleased

    private void txtDescCategoriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescCategoriaKeyReleased
        // TODO add your handling code here:
        Character caracter = new Character(evt.getKeyChar());

        if (!Utilitario.esAlphanumerico(caracter)) {
                    String texto = "";
                    for (int i = 0; i < txtDescCategoria.getText().length(); i++)
                        if (Utilitario.esAlphanumerico(new Character(txtDescCategoria.getText().charAt(i))))
                            texto += txtDescCategoria.getText().charAt(i);
                        txtDescCategoria.setText(texto);
                txtDescCategoria.getToolkit().beep();
        }
    }//GEN-LAST:event_txtDescCategoriaKeyReleased

    /**
    * @param args the command line arguments
    */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblIdCategoria;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtDescCategoria;
    private javax.swing.JTextField txtIdCategoria;
    private javax.swing.JTextField txtNomCategoria;
    // End of variables declaration//GEN-END:variables

}
